const modal=document.getElementById("modal"),mount=document.getElementById("gameMount"),close=document.getElementById("close"),score=document.getElementById("score");let seconds=0;setInterval(()=>{seconds++;score.textContent=Math.floor(seconds/60)+" min session"},1000);
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openGame(b.dataset.open));close.onclick=()=>modal.classList.remove("show");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("show")};
document.getElementById("themeBtn").onclick=()=>document.body.classList.toggle("dark");

function openGame(game){modal.classList.add("show");if(game==="bubbles")bubbles();if(game==="breath")breath();if(game==="memory")memory();if(game==="flow")flow()}
function shell(title,sub,content){mount.innerHTML=`<div class="game-ui"><span class="eyebrow">MIVORA · MINI GAME</span><h2>${title}</h2><p>${sub}</p>${content}</div>`}

function bubbles(){shell("Bubble Drift","Pop 15 bubbles. Take your time.",'<div class="bubble-board" id="board"></div><b id="bubbleScore">0 / 15</b>');const board=document.getElementById("board"),out=document.getElementById("bubbleScore");let n=0;function spawn(){const b=document.createElement("button");b.className="bubble";let s=28+Math.random()*60;b.style.cssText=`width:${s}px;height:${s}px;left:${Math.random()*(100-s/2)}%;top:${Math.random()*(100-s/2)}%;`;b.onclick=()=>{n++;out.textContent=n+" / 15";b.remove();if(n<15)spawn();else out.textContent="Done ✦ You made space."};board.appendChild(b)}for(let i=0;i<4;i++)spawn()}

function breath(){shell("Slow Breath","Breathe with the circle. Inhale as it grows, exhale as it shrinks.",'<div class="breath-game"><div class="big-breath"></div><div class="breath-label" id="breathLabel">Inhale</div></div><button class="game-btn" onclick="close.click()">Finish session</button>');let l=document.getElementById("breathLabel");let on=true;setInterval(()=>{on=!on;l.textContent=on?"Inhale":"Exhale"},5000)}

function memory(){const icons=["✦","○","◇","☾","✿","△","☁","♡"],deck=[...icons,...icons].sort(()=>Math.random()-.5);shell("Soft Match","Find every pair. No timer.",'<div class="memory-board" id="mem"></div><b id="memScore">0 pairs</b>');const board=document.getElementById("mem"),out=document.getElementById("memScore");let first=null,lock=false,pairs=0;deck.forEach((x,i)=>{const b=document.createElement("button");b.className="memory-card";b.textContent=x;b.onclick=()=>{if(lock||b.classList.contains("open"))return;b.classList.add("open");if(!first){first=b;first.dataset.x=x;return}if(first.dataset.x===x){pairs++;out.textContent=pairs+" pairs";first=null;if(pairs===8)out.textContent="Complete ✦"}else{lock=true;setTimeout(()=>{b.classList.remove("open");first.classList.remove("open");first=null;lock=false},650)}};board.appendChild(b)})}

function flow(){shell("Color Flow","Tap the colors in the order shown below.",'<div class="flow-board" id="flow"></div><p id="flowText">Order: leaf → sky → sand → light</p>');const colors=["leaf","sky","sand","light"],board=document.getElementById("flow"),out=document.getElementById("flowText");let i=0;["light","dark","leaf","sky","sand","muted"].sort(()=>Math.random()-.5).forEach(c=>{const b=document.createElement("button");b.className="flow-dot "+c;b.onclick=()=>{if(c===colors[i]){i++;b.style.opacity=".35";if(i===colors.length)out.textContent="Flow complete ✦";else out.textContent="Good. Next: "+colors[i]}else{out.textContent="No rush. Start again.";i=0;document.querySelectorAll(".flow-dot").forEach(x=>x.style.opacity="1")}};board.appendChild(b)})}